# Generated by Django 4.0.1 on 2022-02-21 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_users_userstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='userstatus',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
